name: focus
description: A new Flutter application for the purpose of doing customized breath meditations

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1
  flutter_riverpod: ^1.0.3
  assets_audio_player: ^3.0.5
  numberpicker: ^2.1.1
  another_flushbar: ^1.10.29
  adaptive_dialog: ^1.8.0+1
  simple_logger: ^1.9.0+1
  flutter_slidable: ^2.0.0
  percent_indicator: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.2.1
  confetti: ^0.7.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600



